// Каталог для сайта и поиска: категории по порядку показа, в каждой — иконки по порядку показа,
// у иконки — русское название и слова для поиска (английские и русские синонимы).
// Сборка сайта (tools/site.mjs) сверяет каталог с src/icons.mjs: каждая иконка — ровно в одной категории.
export const CATEGORIES = [
  { id: 'actions', ru: 'Действия', en: 'Actions', icons: {
    'plus': ['плюс', 'add new create добавить создать'],
    'minus': ['минус', 'remove subtract убрать'],
    'x': ['крестик', 'close cancel delete закрыть отмена удалить'],
    'check': ['галочка', 'ok done confirm готово подтвердить'],
    'check-check': ['две галочки', 'read all done прочитано'],
    'circle-plus': ['плюс в круге', 'add добавить'],
    'circle-minus': ['минус в круге', 'remove убрать'],
    'square-plus': ['плюс в квадрате', 'add добавить'],
    'square-minus': ['минус в квадрате', 'remove убрать'],
    'square-x': ['крестик в квадрате', 'close delete закрыть'],
    'search': ['поиск', 'find magnifier лупа найти'],
    'zoom-in': ['приблизить', 'magnify увеличить лупа'],
    'zoom-out': ['отдалить', 'уменьшить лупа'],
    'pencil': ['карандаш', 'edit write править изменить'],
    'pencil-line': ['карандаш с чертой', 'sign signature подпись'],
    'square-pen': ['правка', 'edit write изменить'],
    'copy': ['копировать', 'duplicate дублировать'],
    'scissors': ['ножницы', 'cut вырезать'],
    'trash': ['корзина для мусора', 'delete remove bin удалить мусор'],
    'save': ['сохранить', 'disk floppy дискета'],
    'undo': ['отменить', 'back назад'],
    'redo': ['вернуть', 'repeat повторить'],
    'refresh': ['обновить', 'reload sync перезагрузить'],
    'upload': ['выгрузить', 'upload send отправить загрузить'],
    'download': ['скачать', 'download save загрузка'],
    'external-link': ['внешняя ссылка', 'open new tab открыть'],
    'link': ['ссылка', 'url chain цепь'],
    'pin': ['булавка', 'pin attach закрепить'],
    'funnel': ['фильтр', 'filter воронка'],
    'funnel-x': ['сбросить фильтр', 'clear filter'],
    'log-in': ['войти', 'sign in login вход'],
    'log-out': ['выйти', 'sign out logout выход'],
    'power': ['питание', 'on off shutdown выключить включить'],
  } },
  { id: 'arrows', ru: 'Стрелки', en: 'Arrows', icons: {
    'arrow-up': ['стрелка вверх', 'up'],
    'arrow-right': ['стрелка вправо', 'next forward далее'],
    'arrow-down': ['стрелка вниз', 'down'],
    'arrow-left': ['стрелка влево', 'back previous назад'],
    'arrow-up-right': ['стрелка вправо вверх', 'diagonal диагональ'],
    'arrow-down-right': ['стрелка вправо вниз', 'diagonal диагональ'],
    'arrow-down-left': ['стрелка влево вниз', 'diagonal диагональ'],
    'arrow-up-left': ['стрелка влево вверх', 'diagonal диагональ'],
    'arrow-left-right': ['влево и вправо', 'swap exchange horizontal обмен'],
    'arrow-up-down': ['вверх и вниз', 'sort vertical сортировка'],
    'arrow-down-to-line': ['вниз до черты', 'bottom end в конец'],
    'chevron-up': ['шеврон вверх', 'caret collapse уголок'],
    'chevron-right': ['шеврон вправо', 'caret next уголок'],
    'chevron-down': ['шеврон вниз', 'caret expand уголок'],
    'chevron-left': ['шеврон влево', 'caret back уголок'],
    'chevrons-up': ['двойной шеврон вверх', 'top в начало'],
    'chevrons-right': ['двойной шеврон вправо', 'last в конец'],
    'chevrons-down': ['двойной шеврон вниз', 'bottom в конец'],
    'chevrons-left': ['двойной шеврон влево', 'first в начало'],
    'caret-up': ['треугольник вверх', 'collapse свернуть'],
    'caret-down': ['треугольник вниз', 'dropdown expand раскрыть'],
    'circle-arrow-up': ['стрелка вверх в круге', 'up'],
    'circle-arrow-right': ['стрелка вправо в круге', 'next далее'],
    'circle-arrow-down': ['стрелка вниз в круге', 'down'],
    'circle-arrow-left': ['стрелка влево в круге', 'back назад'],
    'corner-down-left': ['поворот вниз влево', 'enter return ввод'],
    'corner-down-right': ['поворот вниз вправо', 'indent отступ'],
    'reply': ['ответить', 'reply back'],
    'forward': ['переслать', 'forward share'],
    'rotate-cw': ['повернуть по часовой', 'rotate clockwise'],
    'rotate-ccw': ['повернуть против часовой', 'rotate reset сброс'],
    'repeat': ['повтор', 'loop цикл'],
    'shuffle': ['перемешать', 'random случайно'],
    'move': ['переместить', 'drag arrows перетащить'],
    'merge': ['свести вместе', 'join collapse склеить объединить'],
  } },
  { id: 'interface', ru: 'Интерфейс', en: 'Interface', icons: {
    'menu': ['меню', 'hamburger бургер'],
    'dots': ['ещё', 'more ellipsis точки'],
    'dots-vertical': ['ещё, в столбик', 'more kebab точки'],
    'grip-vertical': ['захват', 'drag handle перетащить'],
    'grip-horizontal': ['захват, поперёк', 'drag handle перетащить'],
    'expand': ['развернуть', 'fullscreen maximize на весь экран'],
    'scan': ['вписать', 'fit frame рамка'],
    'panel-left': ['панель слева', 'sidebar боковая панель'],
    'panel-right': ['панель справа', 'sidebar боковая панель'],
    'window': ['окно', 'app window приложение'],
    'window-play': ['запустить окно', 'run app запуск'],
    'window-terminal': ['консоль', 'terminal command line терминал'],
    'window-pointer': ['конструктор окна', 'designer gui builder'],
    'pointer': ['указатель', 'cursor mouse курсор мышь'],
    'crosshair': ['прицел', 'target aim focus точка'],
    'command': ['клавиша ⌘', 'command mac keyboard shortcut сочетание клавиш'],
    'button': ['кнопка', 'button widget'],
    'input': ['поле ввода', 'text field line edit'],
    'input-number': ['поле для числа', 'spinbox integer счётчик'],
    'input-decimal': ['поле для дробного числа', 'float spinbox'],
    'select': ['выпадающий список', 'combobox dropdown'],
    'textarea': ['многострочное поле', 'text area'],
    'slider': ['ползунок', 'range slider'],
    'sliders': ['ползунки настроек', 'sliders tune settings adjust настройки регулировка'],
    'progress': ['полоса прогресса', 'progress bar loading'],
    'toggle-on': ['переключатель включён', 'switch on'],
    'toggle-off': ['переключатель выключен', 'switch off'],
    'square-check': ['флажок', 'checkbox checked отмечено'],
    'circle-dot': ['радиокнопка', 'radio button option выбор'],
    'table': ['таблица', 'grid table'],
    'grid': ['сетка плиток', 'grid tiles apps view плитки'],
    'layout': ['раскладка', 'layout dashboard панель дашборд'],
    'columns': ['колонки', 'columns layout столбцы'],
    'rows': ['строки', 'rows layout ряды'],
    'tabs': ['вкладки', 'tabs'],
    'fieldset': ['групповая рамка', 'frame group box группа'],
    'widgets': ['виджеты', 'components компоненты'],
    'canvas': ['холст', 'canvas drawing рисование'],
    'sitemap': ['структура', 'hierarchy tree иерархия дерево'],
  } },
  { id: 'text', ru: 'Текст и код', en: 'Text & code', icons: {
    'text': ['текст', 'label lines надпись строки'],
    'align-left': ['выровнять влево', 'text alignment'],
    'align-center': ['выровнять по центру', 'text alignment'],
    'align-right': ['выровнять вправо', 'text alignment'],
    'align-justify': ['выровнять по ширине', 'text alignment'],
    'letter-case': ['регистр', 'aa case буквы'],
    'languages': ['языки', 'languages translate language i18n перевод язык'],
    'font-size': ['размер шрифта', 'text size'],
    'bold': ['жирный', 'bold text format полужирный'],
    'italic': ['курсив', 'italic text format наклонный'],
    'underline': ['подчёркнутый', 'underline text format подчеркнуть'],
    'strikethrough': ['зачёркнутый', 'strikethrough text format зачеркнуть'],
    'list': ['маркированный список', 'list bullets bulleted'],
    'list-checks': ['чек-лист', 'checklist todo tasks задачи список'],
    'list-ordered': ['нумерованный список', 'numbered list'],
    'list-ordered-lightning': ['нумерованный список с молнией', 'quick fast быстрый'],
    'list-ordered-x': ['убрать из списка', 'remove list'],
    'text-search': ['поиск по тексту', 'find in text'],
    'text-search-replace': ['найти и заменить', 'replace'],
    'text-cursor-sparkle': ['автодополнение', 'autocomplete ai cursor курсор'],
    'braces': ['фигурные скобки', 'code json object код переменная'],
    'code': ['код', 'code html xml программирование < >'],
    'slashes': ['комментарий', 'comment //'],
    'slashes-off': ['снять комментарий', 'uncomment'],
    'hash': ['решётка', 'hashtag number номер #'],
    'space': ['пробел', 'whitespace'],
    'sticky-note': ['заметка', 'note стикер'],
    'quote': ['цитата', 'quote blockquote кавычки'],
  } },
  { id: 'files', ru: 'Файлы и данные', en: 'Files & data', icons: {
    'file': ['файл', 'document документ'],
    'files': ['файлы', 'documents copies документы'],
    'file-plus': ['новый файл', 'add create создать'],
    'file-x': ['удалить файл', 'remove delete'],
    'file-text': ['текстовый файл', 'document txt документ'],
    'file-code': ['файл с кодом', 'source code исходник'],
    'file-json': ['файл JSON', 'json data данные'],
    'file-image': ['файл картинки', 'image picture фото'],
    'file-music': ['музыкальный файл', 'audio sound звук'],
    'file-video': ['видеофайл', 'video movie play видео фильм'],
    'file-font': ['файл шрифта', 'font'],
    'file-archive': ['архивный файл', 'zip archive'],
    'file-spreadsheet': ['файл таблицы', 'spreadsheet excel csv'],
    'file-database': ['файл базы данных', 'sql db'],
    'file-info': ['свойства файла', 'properties info'],
    'folder': ['папка', 'directory каталог'],
    'folder-open': ['открытая папка', 'open'],
    'folder-plus': ['новая папка', 'create'],
    'folder-down': ['папка загрузок', 'downloads'],
    'archive': ['архив', 'box storage ящик хранилище'],
    'package': ['пакет', 'box project проект коробка'],
    'database': ['база данных', 'db storage хранилище'],
    'clipboard': ['буфер обмена', 'clipboard планшет'],
    'clipboard-list': ['список дел', 'todo tasks checklist задачи'],
    'clipboard-image': ['картинка в буфере', 'paste image'],
    'clipboard-paste': ['вставить', 'paste'],
    'qr-code': ['QR-код', 'qr scan code'],
  } },
  { id: 'communication', ru: 'Связь', en: 'Communication', icons: {
    'mail': ['письмо', 'email envelope почта конверт'],
    'mail-open': ['открытый конверт', 'mail open read letter письмо прочитано'],
    'newspaper': ['газета', 'news article newspaper новости статья'],
    'inbox': ['входящие', 'mail tray почта'],
    'send': ['отправить', 'paper plane самолётик'],
    'at-sign': ['собачка', 'email mention упоминание @'],
    'paperclip': ['скрепка', 'attachment attach вложение'],
    'phone': ['телефон', 'call звонок'],
    'phone-call': ['звонок', 'phone call calling ringing вызов трубка'],
    'message': ['сообщение', 'chat comment чат комментарий'],
    'message-circle': ['сообщение, круглое', 'chat чат'],
    'message-dots': ['набирает сообщение', 'typing chat чат'],
    'message-circle-question': ['вопрос в чате', 'help faq помощь'],
    'message-reply': ['ответ на сообщение', 'reply'],
    'messages': ['переписка', 'conversation chat диалог'],
    'share': ['поделиться', 'share network'],
    'rss': ['RSS', 'feed подписка лента'],
    'megaphone': ['рупор', 'announcement объявление громкоговоритель'],
    'radio': ['в эфире', 'signal broadcast connected сигнал подключено'],
    'radio-off': ['нет сигнала', 'offline disconnected отключено'],
    'radio-tower': ['радиовышка', 'broadcast antenna трансляция антенна'],
    'bookmark': ['закладка', 'save saved'],
    'flag': ['флажок', 'report mark пожаловаться отметить'],
    'thumbs-up': ['нравится', 'like'],
    'thumbs-down': ['не нравится', 'dislike'],
    'smile': ['улыбка', 'emoji happy смайлик'],
    'frown': ['грусть', 'sad emoji смайлик'],
    'star-repeat': ['повторная подписка', 'resubscribe переподписка звезда'],
  } },
  { id: 'people', ru: 'Люди', en: 'People', icons: {
    'user': ['пользователь', 'person account человек'],
    'users': ['пользователи', 'group team группа команда'],
    'circle-user': ['учётная запись', 'account profile avatar профиль аватар'],
    'user-plus': ['добавить пользователя', 'add user invite пригласить'],
    'user-minus': ['убрать пользователя', 'remove user'],
    'user-check': ['пользователь подтверждён', 'verified user'],
    'user-x': ['пользователь с крестиком', 'ban block remove'],
    'user-off': ['пользователь выключен', 'user off disabled inactive отключён неактивен'],
    'user-cog': ['настройки пользователя', 'user settings account manage cog gear аккаунт управление шестерёнка'],
    'contact': ['контакты', 'contacts address book person адресная книга'],
    'hand': ['ладонь', 'hand stop raise palm рука стоп поднять руку'],
    'accessibility': ['доступность', 'accessibility a11y person universal access инклюзивность'],
  } },
  { id: 'status', ru: 'Статусы и защита', en: 'Status & security', icons: {
    'circle-info': ['информация', 'info сведения'],
    'circle-question': ['вопрос в круге', 'help справка помощь'],
    'circle-alert': ['восклицательный знак в круге', 'alert error внимание'],
    'circle-check': ['галочка в круге', 'success done успех'],
    'circle-x': ['крестик в круге', 'error close cancel ошибка отмена'],
    'triangle-alert': ['внимание', 'warning предупреждение'],
    'octagon-alert': ['стоп-знак', 'error stop ошибка'],
    'badge-check': ['проверено', 'verified подтверждено'],
    'bell': ['колокольчик', 'notification alert уведомление'],
    'bell-ring': ['звонящий колокольчик', 'bell ringing notification alarm active уведомление звонок'],
    'bell-off': ['без уведомлений', 'mute notifications off'],
    'loader': ['загрузка', 'loading spinner ждать'],
    'sleep': ['сон', 'sleep zzz спящий режим'],
    'eye': ['глаз', 'show view visible показать видно'],
    'eye-off': ['скрыто', 'hide invisible спрятать не видно'],
    'ban': ['запрещено', 'block forbidden нельзя'],
    'lock': ['замок', 'locked secure закрыто'],
    'lock-open': ['открытый замок', 'unlocked открыто'],
    'lock-key': ['замок с ключом', 'secret credentials секреты'],
    'key': ['ключ', 'password access пароль доступ'],
    'shield': ['щит', 'protection security защита'],
    'shield-check': ['защищено', 'secure verified'],
    'shield-star': ['щит со звездой', 'moderator модератор'],
    'fingerprint': ['отпечаток пальца', 'biometric touch id личность'],
  } },
  { id: 'media', ru: 'Медиа', en: 'Media', icons: {
    'play': ['воспроизвести', 'start run запуск'],
    'play-fill': ['воспроизвести, заливкой', 'start run запуск'],
    'pause': ['пауза', 'pause'],
    'pause-fill': ['пауза, заливкой', 'pause'],
    'stop': ['стоп', 'stop'],
    'stop-fill': ['стоп, заливкой', 'stop'],
    'record': ['запись', 'rec circle'],
    'record-fill': ['запись, заливкой', 'rec'],
    'rewind': ['перемотка назад', 'rewind back'],
    'rewind-fill': ['перемотка назад, заливкой', 'rewind back'],
    'fast-forward': ['перемотка вперёд', 'fast forward'],
    'fast-forward-fill': ['перемотка вперёд, заливкой', 'fast forward'],
    'skip-back': ['к предыдущему', 'previous track'],
    'skip-back-fill': ['к предыдущему, заливкой', 'previous track'],
    'skip-forward': ['к следующему', 'next track'],
    'skip-forward-fill': ['к следующему, заливкой', 'next track'],
    'circle-play': ['воспроизвести в круге', 'play start'],
    'circle-pause': ['пауза в круге', 'pause'],
    'circle-stop': ['стоп в круге', 'stop'],
    'volume': ['громкость', 'sound audio звук'],
    'volume-x': ['без звука', 'mute sound off'],
    'music': ['нота', 'music audio музыка звук'],
    'mic': ['микрофон', 'record voice голос запись'],
    'mic-off': ['микрофон выключен', 'mute'],
    'headphones': ['наушники', 'audio music support звук'],
    'headset': ['гарнитура', 'headset support call center поддержка наушники с микрофоном'],
    'image': ['картинка', 'picture photo изображение'],
    'media': ['медиафайлы', 'gallery photo video галерея'],
    'camera': ['фотоаппарат', 'photo snapshot фото снимок'],
    'aperture': ['диафрагма', 'lens photo объектив фото'],
    'video-camera': ['видеокамера', 'video record видео'],
    'film': ['киноплёнка', 'movie video фильм'],
    'clapperboard': ['хлопушка', 'movie scene кино сцена'],
    'blend': ['наложение', 'chroma key mix хромакей смешивание'],
  } },
  { id: 'time', ru: 'Время', en: 'Time', icons: {
    'clock': ['часы', 'time время'],
    'history': ['история', 'recent past прошлое недавнее'],
    'hourglass': ['песочные часы', 'wait timer ожидание'],
    'stopwatch': ['секундомер', 'timer таймер'],
    'calendar': ['календарь', 'date дата'],
  } },
  { id: 'commerce', ru: 'Покупки и деньги', en: 'Shopping & money', icons: {
    'shopping-cart': ['тележка', 'cart basket корзина магазин'],
    'shopping-bag': ['сумка для покупок', 'shop bag'],
    'store': ['магазин', 'shop storefront'],
    'receipt': ['чек', 'bill invoice счёт'],
    'ticket': ['билет', 'coupon купон'],
    'tag': ['ярлык', 'label price метка цена'],
    'gift': ['подарок', 'present bonus бонус'],
    'banknote': ['купюра', 'money cash деньги наличные'],
    'credit-card': ['банковская карта', 'payment оплата'],
    'dollar-sign': ['доллар', 'money currency валюта цена'],
    'euro-sign': ['евро', 'euro eur currency валюта цена €'],
    'pound-sign': ['фунт стерлингов', 'pound sterling gbp currency валюта £'],
    'yen-sign': ['иена и юань', 'yen yuan jpy cny currency валюта ¥'],
    'ruble-sign': ['рубль', 'ruble rouble rub currency валюта ₽'],
    'rupee-sign': ['рупия', 'rupee inr currency валюта ₹'],
    'wallet': ['кошелёк', 'money payment деньги'],
    'piggy-bank': ['копилка', 'savings сбережения'],
    'landmark': ['банк', 'bank institution учреждение колонны'],
  } },
  { id: 'places', ru: 'Места и транспорт', en: 'Places & transport', icons: {
    'map-pin': ['метка на карте', 'location place место адрес'],
    'map': ['карта', 'map folded'],
    'compass': ['компас', 'navigation explore направление'],
    'navigation': ['стрелка навигации', 'location direction направление геолокация'],
    'globe': ['глобус', 'world web internet language мир сеть язык'],
    'house': ['дом', 'home main главная'],
    'building': ['здание', 'office company офис организация'],
    'car': ['машина', 'automobile auto автомобиль'],
    'bus': ['автобус', 'transport транспорт'],
    'truck': ['грузовик', 'delivery shipping доставка'],
    'locomotive': ['паровоз', 'train поезд'],
    'sailboat': ['парусник', 'boat sail yacht лодка яхта парус'],
    'ship': ['теплоход', 'ship boat vessel корабль судно'],
    'submarine': ['подводная лодка', 'submarine underwater подлодка'],
    'plane': ['самолёт', 'flight airplane полёт'],
    'rocket': ['ракета', 'launch start запуск'],
  } },
  { id: 'devices', ru: 'Устройства', en: 'Devices', icons: {
    'monitor': ['монитор', 'display screen экран'],
    'laptop': ['ноутбук', 'laptop notebook computer компьютер'],
    'tablet': ['планшет', 'tablet ipad device устройство'],
    'smartphone': ['смартфон', 'smartphone mobile phone мобильный телефон'],
    'watch': ['наручные часы', 'watch wristwatch smartwatch часы'],
    'keyboard': ['клавиатура', 'keyboard typing input ввод'],
    'tv': ['телевизор', 'tv screen экран'],
    'printer': ['принтер', 'print печать'],
    'server': ['сервер', 'hosting rack'],
    'mouse': ['мышь', 'mouse computer компьютерная мышь'],
    'mouse-left': ['левая кнопка мыши', 'mouse left click мышь клик ЛКМ'],
    'mouse-right': ['правая кнопка мыши', 'mouse right click context menu мышь ПКМ контекстное меню'],
    'mouse-middle': ['колесо мыши', 'mouse middle click scroll wheel мышь СКМ колёсико'],
    'speaker': ['колонка', 'speaker audio sound звук динамик'],
    'cpu': ['процессор', 'cpu chip processor микросхема чип'],
    'hard-drive': ['жёсткий диск', 'hard drive disk storage hdd накопитель'],
    'battery': ['батарея', 'battery empty power пустая заряд'],
    'battery-low': ['батарея садится', 'battery low power мало заряда'],
    'battery-medium': ['батарея наполовину', 'battery medium half power заряд'],
    'battery-full': ['батарея заряжена', 'battery full power полный заряд'],
    'battery-charging': ['батарея заряжается', 'battery charging power зарядка'],
    'wifi': ['wi-fi', 'wifi wireless network internet беспроводная сеть интернет вайфай'],
    'wifi-off': ['wi-fi выключен', 'wifi off offline no network нет сети'],
    'bluetooth': ['bluetooth', 'bluetooth wireless блютуз беспроводной'],
    'cast': ['трансляция', 'cast screen mirroring chromecast трансляция на экран'],
    'plug': ['вилка', 'plugin connect подключить'],
  } },
  { id: 'tools', ru: 'Инструменты', en: 'Tools', icons: {
    'gear-6': ['шестерёнка', 'settings cog настройки'],
    'gear-8': ['шестерёнка на 8 зубцов', 'settings cog настройки'],
    'wrench': ['гаечный ключ', 'settings fix настройки починить'],
    'hammer': ['молоток', 'build строить'],
    'ruler': ['линейка', 'measure измерить'],
    'magnet': ['магнит', 'snap attract привязка'],
    'pen-tool': ['перо', 'vector bezier кривые'],
    'brush': ['кисть', 'paint рисовать'],
    'palette': ['палитра', 'colors theme цвета тема'],
    'pipette': ['пипетка', 'color picker eyedropper цвет'],
    'eraser': ['ластик', 'erase clear стереть'],
    'crop': ['кадрировать', 'trim обрезать'],
    'flip-horizontal': ['отразить по горизонтали', 'mirror зеркало'],
    'flip-vertical': ['отразить по вертикали', 'mirror зеркало'],
    'layers': ['слои', 'stack layers'],
    'wand-sparkles': ['волшебная палочка', 'magic auto автоматически'],
    'puzzle': ['пазл', 'plugin extension module расширение модуль'],
    'flask-conical': ['колба', 'lab test experiment эксперимент химия'],
    'bug': ['жук', 'debug error отладка ошибка'],
    'git-branch': ['ветка git', 'branch version control'],
    'git-merge': ['слияние git', 'merge version control'],
  } },
  { id: 'math', ru: 'Графики и математика', en: 'Charts & math', icons: {
    'chart-bar': ['столбчатая диаграмма', 'statistics bar chart статистика'],
    'chart-line': ['график', 'line chart'],
    'chart-pie': ['круговая диаграмма', 'pie chart доля'],
    'activity': ['пульс', 'heartbeat monitor активность'],
    'trending-up': ['рост', 'increase trend'],
    'trending-down': ['спад', 'decrease trend падение'],
    'divide': ['деление', 'divide division разделить ÷'],
    'percent': ['процент', 'percentage discount скидка'],
    'calculator': ['калькулятор', 'calculate посчитать'],
    'square-function': ['функция', 'f(x) formula формула'],
    'square-number': ['число в квадрате', 'number цифра'],
    'number-line': ['числовая прямая', 'number line шкала'],
    'axes': ['оси координат', 'coordinates graph система координат'],
    'unit-circle': ['единичная окружность', 'trigonometry тригонометрия'],
    'fraction-bar': ['полоса дробей', 'fraction дробь доли'],
    'area-grid': ['площадь в клетках', 'area grid клетки'],
    'cube-grid': ['куб из кубиков', 'volume объём'],
    'cube': ['куб', '3d объём'],
    'cube-fill': ['чёрный ящик', 'black box закрытый куб'],
    'conveyor': ['конвейер', 'function machine функция преобразование'],
    'scale': ['весы', 'balance compare сравнение равенство'],
  } },
  { id: 'shapes', ru: 'Фигуры', en: 'Shapes', icons: {
    'square': ['квадрат', 'checkbox empty пустой флажок'],
    'triangle': ['треугольник', 'triangle'],
    'pentagon': ['пятиугольник', 'pentagon'],
    'hexagon': ['шестиугольник', 'hexagon'],
    'star': ['звезда', 'favorite rating избранное оценка'],
    'star-fill': ['звезда, заливкой', 'favorite rating избранное оценка'],
    'star-half': ['половина звезды', 'rating оценка'],
    'heart': ['сердце', 'like favorite любимое'],
    'heart-fill': ['сердце, заливкой', 'like favorite любимое'],
    'heart-half': ['половина сердца', 'health здоровье'],
    'sparkle': ['искра', 'new ai magic новое'],
    'sparkle-fill': ['искра, заливкой', 'new ai magic новое'],
  } },
  { id: 'nature', ru: 'Погода и природа', en: 'Weather & nature', icons: {
    'sun': ['солнце', 'light day weather clear светлая тема день погода ясно'],
    'moon': ['луна', 'night dark ночь тёмная тема'],
    'sunrise': ['восход', 'sunrise morning dawn утро рассвет'],
    'sunset': ['закат', 'sunset evening dusk вечер сумерки'],
    'cloud': ['облако', 'weather cloudy storage погода облачно облачное хранилище'],
    'cloud-rain': ['дождь', 'rain weather cloud погода облако ливень'],
    'cloud-snow': ['снегопад', 'snow weather cloud снег погода облако'],
    'cloud-lightning': ['гроза', 'storm thunder lightning weather молния гром погода'],
    'wind': ['ветер', 'air weather breeze воздух погода'],
    'snowflake': ['снежинка', 'snow winter cold freeze снег зима холод заморозка'],
    'droplet': ['капля', 'water liquid humidity drop вода влажность жидкость'],
    'umbrella': ['зонт', 'rain protection insurance дождь защита страховка'],
    'thermometer': ['термометр', 'temperature weather температура погода градусник'],
    'flame': ['пламя', 'fire hot burn trending огонь горячее популярное'],
    'leaf': ['лист', 'eco nature plant эко природа растение'],
    'tree': ['дерево', 'nature park forest природа парк лес'],
    'tree-pine': ['ель', 'pine christmas forest ёлка хвоя лес'],
    'paw-print': ['след лапы', 'pet animal dog cat питомец животное собака кошка'],
  } },
  { id: 'objects', ru: 'Предметы', en: 'Objects', icons: {
    'lightning': ['молния', 'power fast energy быстро энергия'],
    'bulb': ['лампочка', 'idea tip идея подсказка'],
    'book': ['книга', 'read читать'],
    'book-open': ['открытая книга', 'read tutorial учебник читать'],
    'books': ['книги', 'library docs библиотека документация'],
    'graduation-cap': ['выпускная шапочка', 'education school учёба образование'],
    'briefcase': ['портфель', 'work job работа дело'],
    'award': ['награда', 'medal badge медаль приз'],
    'crown': ['корона', 'owner king vip владелец'],
    'gem': ['драгоценный камень', 'diamond premium алмаз'],
    'target': ['мишень', 'goal aim цель'],
    'dice': ['игральный кубик', 'random game случайность игра'],
    'party-popper': ['хлопушка-конфетти', 'celebration party праздник'],
    'coffee': ['кофе', 'cup break чашка перерыв'],
    'chef-hat': ['поварской колпак', 'cooking recipe рецепт кухня'],
    'anchor': ['якорь', 'port harbor порт'],
    'life-buoy': ['спасательный круг', 'help support помощь поддержка'],
    'sword': ['меч', 'moderator weapon модератор'],
    'robot': ['робот', 'bot ai бот'],
    'turtle': ['черепаха', 'slow turtle graphics медленно черепашья графика'],
  } },
];
