// Иконки, чей рисунок совпадает с иконкой другого открытого набора: наше имя → имя там. Совпадение — доля общих
// пикселей линии 0,9 и больше (сверка на кухне: как есть, со сдвигом и в зеркале). Большинство — простые знаки (плюс,
// шевроны, стрелки, лупа), они у всех наборов одинаковы; есть и рисунки (наушники, калькулятор, спасательный круг).
// На эти иконки действует и лицензия того набора — тексты и списки в THIRD-PARTY-NOTICES.md (списки собирает
// tools/site.mjs), сайт помечает такие иконки в карточке.

// Lucide (https://lucide.dev): ISC, части из Feather — MIT; сверка с lucide-static 0.544.0, 27.09.2026
export const LUCIDE = {
  'aperture': 'aperture',
  'archive': 'archive',
  'arrow-down-to-line': 'arrow-down-to-line',
  'arrow-left-right': 'arrow-left-right',
  'arrow-up-down': 'arrow-up-down',
  'at-sign': 'at-sign',
  'ban': 'ban',
  'banknote': 'banknote',
  'bookmark': 'bookmark',
  'building': 'building',
  'calculator': 'calculator',
  'check': 'check',
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-up': 'chevron-up',
  'chevrons-down': 'chevrons-down',
  'chevrons-left': 'chevrons-left',
  'chevrons-right': 'chevrons-right',
  'chevrons-up': 'chevrons-up',
  'circle-alert': 'alert-circle',
  'circle-check': 'check-circle-2',
  'circle-info': 'info',
  'circle-minus': 'circle-minus',
  'circle-pause': 'circle-pause',
  'circle-play': 'circle-play',
  'circle-plus': 'circle-plus',
  'circle-question': 'circle-help',
  'circle-stop': 'circle-stop',
  'circle-x': 'circle-x',
  'clipboard': 'clipboard',
  'clock': 'clock-2',
  'code': 'code',
  'columns': 'columns-3',
  'command': 'command',
  'corner-down-left': 'corner-down-left',
  'corner-down-right': 'corner-down-right',
  'credit-card': 'credit-card',
  'crop': 'crop',
  'crosshair': 'locate-fixed',
  'divide': 'divide',
  'dollar-sign': 'dollar-sign',
  'download': 'download',
  'expand': 'expand',
  'eye': 'eye',
  'file': 'file',
  'file-code': 'file-code',
  'file-plus': 'file-plus',
  'file-x': 'file-x',
  'folder': 'folder',
  'folder-down': 'folder-down',
  'folder-plus': 'folder-plus',
  'forward': 'corner-up-right',
  'frown': 'frown',
  'git-branch': 'git-branch',
  'git-merge': 'git-merge',
  'grid': 'layout-grid',
  'hash': 'hash',
  'headphones': 'headphones',
  'input': 'rectangle-horizontal',
  'layout': 'layout-dashboard',
  'life-buoy': 'life-buoy',
  'mail': 'mail',
  'map': 'map',
  'mic': 'mic',
  'minus': 'minus',
  'monitor': 'monitor',
  'move': 'move',
  'music': 'music',
  'navigation': 'navigation',
  'panel-left': 'panel-left',
  'panel-right': 'panel-right',
  'percent': 'percent',
  'phone': 'phone',
  'plus': 'plus',
  'printer': 'printer',
  'redo': 'redo-2',
  'repeat': 'repeat',
  'reply': 'corner-up-left',
  'rows': 'panels-top-bottom',
  'scan': 'maximize',
  'search': 'search',
  'share': 'share-2',
  'smile': 'smile',
  'square': 'square',
  'square-function': 'function-square',
  'square-minus': 'minus-square',
  'square-plus': 'plus-square',
  'square-x': 'square-x',
  'sun': 'sun',
  'target': 'target',
  'ticket': 'ticket',
  'trending-down': 'trending-down',
  'trending-up': 'trending-up',
  'truck': 'truck',
  'turtle': 'turtle',
  'undo': 'undo-2',
  'upload': 'upload',
  'x': 'x',
  'zoom-in': 'zoom-in',
  'zoom-out': 'zoom-out',
};

// Tabler Icons (https://tabler.io/icons): MIT; сверка с @tabler/icons 3.35.0 (outline), 28.09.2026
export const TABLER = {
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-up': 'chevron-up',
  'columns': 'columns-3',
  'cube': 'box',
  'database': 'database',
  'divide': 'divide',
  'heart': 'heart',
  'magnet': 'magnet',
  'map-pin': 'map-pin',
  'menu': 'menu-2',
  'minus': 'minus',
  'plus': 'plus',
  'square': 'square',
  'square-minus': 'wash-dry-flat',
  'square-plus': 'square-plus',
  'square-x': 'square-x',
  'stop': 'crop-1-1',
  'sun': 'sun-high',
  'textarea': 'article',
  'toggle-off': 'toggle-left',
  'toggle-on': 'toggle-left',
  'x': 'x',
};
